package com.benluvzbacon.ironworks.registry;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registry;
import net.minecraft.registry.Registries;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import com.benluvzbacon.ironworks.Ironworks;

public class ModItemGroups {
    public static final ItemGroup IRONWORKS_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Ironworks.MOD_ID, "main"),
            FabricItemGroup.builder()
                    .icon(() -> new ItemStack(ModItems.BRONZE_GEAR))
                    .displayName(Text.translatable("itemGroup.ironworks.main"))
                    .entries((context, entries) -> {
                        entries.add(ModItems.COPPER_CRUSHED);
                        entries.add(ModItems.COPPER_DUST);
                        entries.add(ModItems.COPPER_NUGGET);
                        entries.add(ModItems.COPPER_PLATE);
                        entries.add(ModItems.COPPER_ROD);
                        entries.add(ModItems.COPPER_WIRE);
                        entries.add(ModItems.COPPER_GEAR);
                        entries.add(ModItems.COPPER_HAMMER);
                        entries.add(ModItems.TIN_RAW);
                        entries.add(ModItems.TIN_ORE);
                        entries.add(ModItems.DEEPSLATE_TIN_ORE);
                        entries.add(ModItems.TIN_CRUSHED);
                        entries.add(ModItems.TIN_DUST);
                        entries.add(ModItems.TIN_INGOT);
                        entries.add(ModItems.TIN_NUGGET);
                        entries.add(ModItems.TIN_PLATE);
                        entries.add(ModItems.TIN_ROD);
                        entries.add(ModItems.TIN_WIRE);
                        entries.add(ModItems.TIN_GEAR);
                        entries.add(ModItems.TIN_BLOCK);
                        entries.add(ModItems.IRON_CRUSHED);
                        entries.add(ModItems.IRON_DUST);
                        entries.add(ModItems.IRON_PLATE);
                        entries.add(ModItems.IRON_ROD);
                        entries.add(ModItems.IRON_WIRE);
                        entries.add(ModItems.IRON_GEAR);
                        entries.add(ModItems.IRON_HAMMER);
                        entries.add(ModItems.IRON_RING);
                        entries.add(ModItems.IRON_SCREW);
                        entries.add(ModItems.IRON_BOLT);
                        entries.add(ModItems.LEAD_RAW);
                        entries.add(ModItems.LEAD_ORE);
                        entries.add(ModItems.DEEPSLATE_LEAD_ORE);
                        entries.add(ModItems.LEAD_CRUSHED);
                        entries.add(ModItems.LEAD_DUST);
                        entries.add(ModItems.LEAD_INGOT);
                        entries.add(ModItems.LEAD_NUGGET);
                        entries.add(ModItems.LEAD_PLATE);
                        entries.add(ModItems.LEAD_ROD);
                        entries.add(ModItems.LEAD_WIRE);
                        entries.add(ModItems.LEAD_GEAR);
                        entries.add(ModItems.LEAD_BLOCK);
                        entries.add(ModItems.ZINC_RAW);
                        entries.add(ModItems.ZINC_ORE);
                        entries.add(ModItems.DEEPSLATE_ZINC_ORE);
                        entries.add(ModItems.ZINC_CRUSHED);
                        entries.add(ModItems.ZINC_DUST);
                        entries.add(ModItems.ZINC_INGOT);
                        entries.add(ModItems.ZINC_NUGGET);
                        entries.add(ModItems.ZINC_PLATE);
                        entries.add(ModItems.ZINC_ROD);
                        entries.add(ModItems.ZINC_WIRE);
                        entries.add(ModItems.ZINC_GEAR);
                        entries.add(ModItems.ZINC_BLOCK);
                        entries.add(ModItems.GOLD_CRUSHED);
                        entries.add(ModItems.GOLD_DUST);
                        entries.add(ModItems.GOLD_PLATE);
                        entries.add(ModItems.GOLD_ROD);
                        entries.add(ModItems.GOLD_WIRE);
                        entries.add(ModItems.GOLD_GEAR);
                        entries.add(ModItems.SILVER_RAW);
                        entries.add(ModItems.SILVER_ORE);
                        entries.add(ModItems.DEEPSLATE_SILVER_ORE);
                        entries.add(ModItems.SILVER_CRUSHED);
                        entries.add(ModItems.SILVER_DUST);
                        entries.add(ModItems.SILVER_INGOT);
                        entries.add(ModItems.SILVER_NUGGET);
                        entries.add(ModItems.SILVER_PLATE);
                        entries.add(ModItems.SILVER_ROD);
                        entries.add(ModItems.SILVER_WIRE);
                        entries.add(ModItems.SILVER_GEAR);
                        entries.add(ModItems.SILVER_BLOCK);
                        entries.add(ModItems.NICKEL_RAW);
                        entries.add(ModItems.NICKEL_ORE);
                        entries.add(ModItems.DEEPSLATE_NICKEL_ORE);
                        entries.add(ModItems.NICKEL_CRUSHED);
                        entries.add(ModItems.NICKEL_DUST);
                        entries.add(ModItems.NICKEL_INGOT);
                        entries.add(ModItems.NICKEL_NUGGET);
                        entries.add(ModItems.NICKEL_PLATE);
                        entries.add(ModItems.NICKEL_ROD);
                        entries.add(ModItems.NICKEL_WIRE);
                        entries.add(ModItems.NICKEL_GEAR);
                        entries.add(ModItems.NICKEL_BLOCK);
                        entries.add(ModItems.COAL_DUST);
                        entries.add(ModItems.CHARCOAL_DUST);
                        entries.add(ModItems.BRONZE_DUST);
                        entries.add(ModItems.BRONZE_INGOT);
                        entries.add(ModItems.BRONZE_NUGGET);
                        entries.add(ModItems.BRONZE_PLATE);
                        entries.add(ModItems.BRONZE_ROD);
                        entries.add(ModItems.BRONZE_WIRE);
                        entries.add(ModItems.BRONZE_GEAR);
                        entries.add(ModItems.BRONZE_BLOCK);
                        entries.add(ModItems.BRONZE_RING);
                        entries.add(ModItems.BRONZE_SCREW);
                        entries.add(ModItems.BRONZE_HAMMER);
                        entries.add(ModItems.BRASS_DUST);
                        entries.add(ModItems.BRASS_INGOT);
                        entries.add(ModItems.BRASS_NUGGET);
                        entries.add(ModItems.BRASS_PLATE);
                        entries.add(ModItems.BRASS_ROD);
                        entries.add(ModItems.BRASS_WIRE);
                        entries.add(ModItems.BRASS_GEAR);
                        entries.add(ModItems.BRASS_BLOCK);
                        entries.add(ModItems.STEEL_DUST);
                        entries.add(ModItems.STEEL_INGOT);
                        entries.add(ModItems.STEEL_NUGGET);
                        entries.add(ModItems.STEEL_PLATE);
                        entries.add(ModItems.STEEL_ROD);
                        entries.add(ModItems.STEEL_WIRE);
                        entries.add(ModItems.STEEL_GEAR);
                        entries.add(ModItems.STEEL_BLOCK);
                        entries.add(ModItems.STEEL_RING);
                        entries.add(ModItems.STEEL_SCREW);
                        entries.add(ModItems.STEEL_HAMMER);
                        entries.add(ModItems.COAL_COKE_DUST);
                        entries.add(ModItems.COAL_COKE_GEM);
                        entries.add(ModItems.COAL_COKE_BLOCK);
                        entries.add(ModItems.ENGINEERING_WRENCH);
                        entries.add(ModItems.BASIC_ELECTRICAL_CIRCUIT);
                        entries.add(ModItems.RUBBER);
                        entries.add(ModItems.RAW_RUBBER_PULP);
                        entries.add(ModItems.BRONZE_FURNACE);
                        entries.add(ModItems.BRONZE_MACERATOR);
                        entries.add(ModItems.BRONZE_ALLOY_SMELTER);
                        entries.add(ModItems.BRONZE_FORGE_HAMMER);
                        entries.add(ModItems.BRONZE_COMPRESSOR);
                        entries.add(ModItems.BRONZE_EXTRACTOR);
                        entries.add(ModItems.BRONZE_ROCK_BREAKER);
                        entries.add(ModItems.STEEL_FURNACE);
                        entries.add(ModItems.STEEL_MACERATOR);
                        entries.add(ModItems.STEEL_ALLOY_SMELTER);
                        entries.add(ModItems.STEEL_FORGE_HAMMER);
                        entries.add(ModItems.STEEL_COMPRESSOR);
                        entries.add(ModItems.STEEL_EXTRACTOR);
                        entries.add(ModItems.STEEL_ROCK_BREAKER);
                    })
                    .build());
                    
    public static void initialize() {}
}
