package com.benluvzbacon.ironworks.registry;

import net.minecraft.item.Item;
import net.minecraft.item.BlockItem;
import net.minecraft.registry.Registry;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import com.benluvzbacon.ironworks.Ironworks;

public class ModItems {
    public static final Item COPPER_CRUSHED = registerItem("copper_crushed", new Item(new Item.Settings()));
    public static final Item COPPER_DUST = registerItem("copper_dust", new Item(new Item.Settings()));
    public static final Item COPPER_NUGGET = registerItem("copper_nugget", new Item(new Item.Settings()));
    public static final Item COPPER_PLATE = registerItem("copper_plate", new Item(new Item.Settings()));
    public static final Item COPPER_ROD = registerItem("copper_rod", new Item(new Item.Settings()));
    public static final Item COPPER_WIRE = registerItem("copper_wire", new Item(new Item.Settings()));
    public static final Item COPPER_GEAR = registerItem("copper_gear", new Item(new Item.Settings()));
    public static final Item COPPER_HAMMER = registerItem("copper_hammer", new Item(new Item.Settings()));
    public static final Item TIN_RAW = registerItem("tin_raw", new Item(new Item.Settings()));
    public static final Item TIN_CRUSHED = registerItem("tin_crushed", new Item(new Item.Settings()));
    public static final Item TIN_DUST = registerItem("tin_dust", new Item(new Item.Settings()));
    public static final Item TIN_INGOT = registerItem("tin_ingot", new Item(new Item.Settings()));
    public static final Item TIN_NUGGET = registerItem("tin_nugget", new Item(new Item.Settings()));
    public static final Item TIN_PLATE = registerItem("tin_plate", new Item(new Item.Settings()));
    public static final Item TIN_ROD = registerItem("tin_rod", new Item(new Item.Settings()));
    public static final Item TIN_WIRE = registerItem("tin_wire", new Item(new Item.Settings()));
    public static final Item TIN_GEAR = registerItem("tin_gear", new Item(new Item.Settings()));
    public static final Item IRON_CRUSHED = registerItem("iron_crushed", new Item(new Item.Settings()));
    public static final Item IRON_DUST = registerItem("iron_dust", new Item(new Item.Settings()));
    public static final Item IRON_PLATE = registerItem("iron_plate", new Item(new Item.Settings()));
    public static final Item IRON_ROD = registerItem("iron_rod", new Item(new Item.Settings()));
    public static final Item IRON_WIRE = registerItem("iron_wire", new Item(new Item.Settings()));
    public static final Item IRON_GEAR = registerItem("iron_gear", new Item(new Item.Settings()));
    public static final Item IRON_HAMMER = registerItem("iron_hammer", new Item(new Item.Settings()));
    public static final Item IRON_RING = registerItem("iron_ring", new Item(new Item.Settings()));
    public static final Item IRON_SCREW = registerItem("iron_screw", new Item(new Item.Settings()));
    public static final Item IRON_BOLT = registerItem("iron_bolt", new Item(new Item.Settings()));
    public static final Item LEAD_RAW = registerItem("lead_raw", new Item(new Item.Settings()));
    public static final Item LEAD_CRUSHED = registerItem("lead_crushed", new Item(new Item.Settings()));
    public static final Item LEAD_DUST = registerItem("lead_dust", new Item(new Item.Settings()));
    public static final Item LEAD_INGOT = registerItem("lead_ingot", new Item(new Item.Settings()));
    public static final Item LEAD_NUGGET = registerItem("lead_nugget", new Item(new Item.Settings()));
    public static final Item LEAD_PLATE = registerItem("lead_plate", new Item(new Item.Settings()));
    public static final Item LEAD_ROD = registerItem("lead_rod", new Item(new Item.Settings()));
    public static final Item LEAD_WIRE = registerItem("lead_wire", new Item(new Item.Settings()));
    public static final Item LEAD_GEAR = registerItem("lead_gear", new Item(new Item.Settings()));
    public static final Item ZINC_RAW = registerItem("zinc_raw", new Item(new Item.Settings()));
    public static final Item ZINC_CRUSHED = registerItem("zinc_crushed", new Item(new Item.Settings()));
    public static final Item ZINC_DUST = registerItem("zinc_dust", new Item(new Item.Settings()));
    public static final Item ZINC_INGOT = registerItem("zinc_ingot", new Item(new Item.Settings()));
    public static final Item ZINC_NUGGET = registerItem("zinc_nugget", new Item(new Item.Settings()));
    public static final Item ZINC_PLATE = registerItem("zinc_plate", new Item(new Item.Settings()));
    public static final Item ZINC_ROD = registerItem("zinc_rod", new Item(new Item.Settings()));
    public static final Item ZINC_WIRE = registerItem("zinc_wire", new Item(new Item.Settings()));
    public static final Item ZINC_GEAR = registerItem("zinc_gear", new Item(new Item.Settings()));
    public static final Item GOLD_CRUSHED = registerItem("gold_crushed", new Item(new Item.Settings()));
    public static final Item GOLD_DUST = registerItem("gold_dust", new Item(new Item.Settings()));
    public static final Item GOLD_PLATE = registerItem("gold_plate", new Item(new Item.Settings()));
    public static final Item GOLD_ROD = registerItem("gold_rod", new Item(new Item.Settings()));
    public static final Item GOLD_WIRE = registerItem("gold_wire", new Item(new Item.Settings()));
    public static final Item GOLD_GEAR = registerItem("gold_gear", new Item(new Item.Settings()));
    public static final Item SILVER_RAW = registerItem("silver_raw", new Item(new Item.Settings()));
    public static final Item SILVER_CRUSHED = registerItem("silver_crushed", new Item(new Item.Settings()));
    public static final Item SILVER_DUST = registerItem("silver_dust", new Item(new Item.Settings()));
    public static final Item SILVER_INGOT = registerItem("silver_ingot", new Item(new Item.Settings()));
    public static final Item SILVER_NUGGET = registerItem("silver_nugget", new Item(new Item.Settings()));
    public static final Item SILVER_PLATE = registerItem("silver_plate", new Item(new Item.Settings()));
    public static final Item SILVER_ROD = registerItem("silver_rod", new Item(new Item.Settings()));
    public static final Item SILVER_WIRE = registerItem("silver_wire", new Item(new Item.Settings()));
    public static final Item SILVER_GEAR = registerItem("silver_gear", new Item(new Item.Settings()));
    public static final Item NICKEL_RAW = registerItem("nickel_raw", new Item(new Item.Settings()));
    public static final Item NICKEL_CRUSHED = registerItem("nickel_crushed", new Item(new Item.Settings()));
    public static final Item NICKEL_DUST = registerItem("nickel_dust", new Item(new Item.Settings()));
    public static final Item NICKEL_INGOT = registerItem("nickel_ingot", new Item(new Item.Settings()));
    public static final Item NICKEL_NUGGET = registerItem("nickel_nugget", new Item(new Item.Settings()));
    public static final Item NICKEL_PLATE = registerItem("nickel_plate", new Item(new Item.Settings()));
    public static final Item NICKEL_ROD = registerItem("nickel_rod", new Item(new Item.Settings()));
    public static final Item NICKEL_WIRE = registerItem("nickel_wire", new Item(new Item.Settings()));
    public static final Item NICKEL_GEAR = registerItem("nickel_gear", new Item(new Item.Settings()));
    public static final Item COAL_DUST = registerItem("coal_dust", new Item(new Item.Settings()));
    public static final Item CHARCOAL_DUST = registerItem("charcoal_dust", new Item(new Item.Settings()));
    public static final Item BRONZE_DUST = registerItem("bronze_dust", new Item(new Item.Settings()));
    public static final Item BRONZE_INGOT = registerItem("bronze_ingot", new Item(new Item.Settings()));
    public static final Item BRONZE_NUGGET = registerItem("bronze_nugget", new Item(new Item.Settings()));
    public static final Item BRONZE_PLATE = registerItem("bronze_plate", new Item(new Item.Settings()));
    public static final Item BRONZE_ROD = registerItem("bronze_rod", new Item(new Item.Settings()));
    public static final Item BRONZE_WIRE = registerItem("bronze_wire", new Item(new Item.Settings()));
    public static final Item BRONZE_GEAR = registerItem("bronze_gear", new Item(new Item.Settings()));
    public static final Item BRONZE_RING = registerItem("bronze_ring", new Item(new Item.Settings()));
    public static final Item BRONZE_SCREW = registerItem("bronze_screw", new Item(new Item.Settings()));
    public static final Item BRONZE_HAMMER = registerItem("bronze_hammer", new Item(new Item.Settings()));
    public static final Item BRASS_DUST = registerItem("brass_dust", new Item(new Item.Settings()));
    public static final Item BRASS_INGOT = registerItem("brass_ingot", new Item(new Item.Settings()));
    public static final Item BRASS_NUGGET = registerItem("brass_nugget", new Item(new Item.Settings()));
    public static final Item BRASS_PLATE = registerItem("brass_plate", new Item(new Item.Settings()));
    public static final Item BRASS_ROD = registerItem("brass_rod", new Item(new Item.Settings()));
    public static final Item BRASS_WIRE = registerItem("brass_wire", new Item(new Item.Settings()));
    public static final Item BRASS_GEAR = registerItem("brass_gear", new Item(new Item.Settings()));
    public static final Item STEEL_DUST = registerItem("steel_dust", new Item(new Item.Settings()));
    public static final Item STEEL_INGOT = registerItem("steel_ingot", new Item(new Item.Settings()));
    public static final Item STEEL_NUGGET = registerItem("steel_nugget", new Item(new Item.Settings()));
    public static final Item STEEL_PLATE = registerItem("steel_plate", new Item(new Item.Settings()));
    public static final Item STEEL_ROD = registerItem("steel_rod", new Item(new Item.Settings()));
    public static final Item STEEL_WIRE = registerItem("steel_wire", new Item(new Item.Settings()));
    public static final Item STEEL_GEAR = registerItem("steel_gear", new Item(new Item.Settings()));
    public static final Item STEEL_RING = registerItem("steel_ring", new Item(new Item.Settings()));
    public static final Item STEEL_SCREW = registerItem("steel_screw", new Item(new Item.Settings()));
    public static final Item STEEL_HAMMER = registerItem("steel_hammer", new Item(new Item.Settings()));
    public static final Item COAL_COKE_DUST = registerItem("coal_coke_dust", new Item(new Item.Settings()));
    public static final Item COAL_COKE_GEM = registerItem("coal_coke_gem", new Item(new Item.Settings()));
    public static final Item ENGINEERING_WRENCH = registerItem("engineering_wrench", new Item(new Item.Settings()));
    public static final Item BASIC_ELECTRICAL_CIRCUIT = registerItem("basic_electrical_circuit", new Item(new Item.Settings()));
    public static final Item RUBBER = registerItem("rubber", new Item(new Item.Settings()));
    public static final Item RAW_RUBBER_PULP = registerItem("raw_rubber_pulp", new Item(new Item.Settings()));
    public static final Item TIN_ORE = registerItem("tin_ore", new BlockItem(ModBlocks.TIN_ORE, new Item.Settings()));
    public static final Item DEEPSLATE_TIN_ORE = registerItem("deepslate_tin_ore", new BlockItem(ModBlocks.DEEPSLATE_TIN_ORE, new Item.Settings()));
    public static final Item TIN_BLOCK = registerItem("tin_block", new BlockItem(ModBlocks.TIN_BLOCK, new Item.Settings()));
    public static final Item LEAD_ORE = registerItem("lead_ore", new BlockItem(ModBlocks.LEAD_ORE, new Item.Settings()));
    public static final Item DEEPSLATE_LEAD_ORE = registerItem("deepslate_lead_ore", new BlockItem(ModBlocks.DEEPSLATE_LEAD_ORE, new Item.Settings()));
    public static final Item LEAD_BLOCK = registerItem("lead_block", new BlockItem(ModBlocks.LEAD_BLOCK, new Item.Settings()));
    public static final Item ZINC_ORE = registerItem("zinc_ore", new BlockItem(ModBlocks.ZINC_ORE, new Item.Settings()));
    public static final Item DEEPSLATE_ZINC_ORE = registerItem("deepslate_zinc_ore", new BlockItem(ModBlocks.DEEPSLATE_ZINC_ORE, new Item.Settings()));
    public static final Item ZINC_BLOCK = registerItem("zinc_block", new BlockItem(ModBlocks.ZINC_BLOCK, new Item.Settings()));
    public static final Item SILVER_ORE = registerItem("silver_ore", new BlockItem(ModBlocks.SILVER_ORE, new Item.Settings()));
    public static final Item DEEPSLATE_SILVER_ORE = registerItem("deepslate_silver_ore", new BlockItem(ModBlocks.DEEPSLATE_SILVER_ORE, new Item.Settings()));
    public static final Item SILVER_BLOCK = registerItem("silver_block", new BlockItem(ModBlocks.SILVER_BLOCK, new Item.Settings()));
    public static final Item NICKEL_ORE = registerItem("nickel_ore", new BlockItem(ModBlocks.NICKEL_ORE, new Item.Settings()));
    public static final Item DEEPSLATE_NICKEL_ORE = registerItem("deepslate_nickel_ore", new BlockItem(ModBlocks.DEEPSLATE_NICKEL_ORE, new Item.Settings()));
    public static final Item NICKEL_BLOCK = registerItem("nickel_block", new BlockItem(ModBlocks.NICKEL_BLOCK, new Item.Settings()));
    public static final Item BRONZE_BLOCK = registerItem("bronze_block", new BlockItem(ModBlocks.BRONZE_BLOCK, new Item.Settings()));
    public static final Item BRASS_BLOCK = registerItem("brass_block", new BlockItem(ModBlocks.BRASS_BLOCK, new Item.Settings()));
    public static final Item STEEL_BLOCK = registerItem("steel_block", new BlockItem(ModBlocks.STEEL_BLOCK, new Item.Settings()));
    public static final Item COAL_COKE_BLOCK = registerItem("coal_coke_block", new BlockItem(ModBlocks.COAL_COKE_BLOCK, new Item.Settings()));
    public static final Item BRONZE_FURNACE = registerItem("bronze_furnace", new BlockItem(ModBlocks.BRONZE_FURNACE, new Item.Settings()));
    public static final Item BRONZE_MACERATOR = registerItem("bronze_macerator", new BlockItem(ModBlocks.BRONZE_MACERATOR, new Item.Settings()));
    public static final Item BRONZE_ALLOY_SMELTER = registerItem("bronze_alloy_smelter", new BlockItem(ModBlocks.BRONZE_ALLOY_SMELTER, new Item.Settings()));
    public static final Item BRONZE_FORGE_HAMMER = registerItem("bronze_forge_hammer", new BlockItem(ModBlocks.BRONZE_FORGE_HAMMER, new Item.Settings()));
    public static final Item BRONZE_COMPRESSOR = registerItem("bronze_compressor", new BlockItem(ModBlocks.BRONZE_COMPRESSOR, new Item.Settings()));
    public static final Item BRONZE_EXTRACTOR = registerItem("bronze_extractor", new BlockItem(ModBlocks.BRONZE_EXTRACTOR, new Item.Settings()));
    public static final Item BRONZE_ROCK_BREAKER = registerItem("bronze_rock_breaker", new BlockItem(ModBlocks.BRONZE_ROCK_BREAKER, new Item.Settings()));
    public static final Item STEEL_FURNACE = registerItem("steel_furnace", new BlockItem(ModBlocks.STEEL_FURNACE, new Item.Settings()));
    public static final Item STEEL_MACERATOR = registerItem("steel_macerator", new BlockItem(ModBlocks.STEEL_MACERATOR, new Item.Settings()));
    public static final Item STEEL_ALLOY_SMELTER = registerItem("steel_alloy_smelter", new BlockItem(ModBlocks.STEEL_ALLOY_SMELTER, new Item.Settings()));
    public static final Item STEEL_FORGE_HAMMER = registerItem("steel_forge_hammer", new BlockItem(ModBlocks.STEEL_FORGE_HAMMER, new Item.Settings()));
    public static final Item STEEL_COMPRESSOR = registerItem("steel_compressor", new BlockItem(ModBlocks.STEEL_COMPRESSOR, new Item.Settings()));
    public static final Item STEEL_EXTRACTOR = registerItem("steel_extractor", new BlockItem(ModBlocks.STEEL_EXTRACTOR, new Item.Settings()));
    public static final Item STEEL_ROCK_BREAKER = registerItem("steel_rock_breaker", new BlockItem(ModBlocks.STEEL_ROCK_BREAKER, new Item.Settings()));

    private static Item registerItem(String name, Item item) {
        return Registry.register(Registries.ITEM, Identifier.of(Ironworks.MOD_ID, name), item);
    }
    public static void initialize() {}
}
